#!/bin/sh
#
#          A simple 'aws' command 'axs' written in POSIX sh 
#               axs(access) to aws(amazon web services)
# axs to Amazon Polly Speech
# Original author: BRAVEMAN LONGBRIDGE, 2016
# powerd by POSIX原理主義 
########################################################################

########################################################################
# 初期設定
########################################################################
# === 初期化 =========================================================
set -u                                                                 #
umask 0022                                                             #
unset IFS                                                              #
export LC_ALL='C'                                                      #
export PATH="/usr/local/shellshoccar/bin:$PATH"
export PATH="$(command -p getconf PATH):$PATH"
# === 必要なプログラムの存在を確認する =============================
# --- 1.符号化コマンド (OpenSSL                                         #                                       
if   command -v openssl >/dev/null; then                               #
  CMD_OSSL='openssl'                                                   #
else                                                                   #
  error_exit 1 'OpenSSL command is not found.'                         #
fi                                                                     #
# --- 2.HTTPアクセスコマンド（wgetまたはcurl                             #
if   command -v curl    >/dev/null; then                               #
  CMD_CURL='curl'                                                      #
elif command -v wget    >/dev/null; then                               #
  CMD_WGET='wget'                                                      #
else                                                                   #
  error_exit 1 'No HTTP-GET/POST command found.'                       #
fi                                                                     #
########################################################################
# パラメーター 適宜変更してください。ファイルor標準入力からの読み込み予定
# オプションでサービス選択可能にするつもり
# example: -e:ec2 -i:IAM -s:S3 -p:pollyなど
########################################################################
u_key="$(cat ~/.aws/credentials                                        | 
         grep key_id                                                   | 
         awk 'NR==1{print $3}'                                         )"
u_secret="$(cat ~/.aws/credentials                                     | 
            grep secret                                                | 
            awk 'NR==1{print $3}'                                      )"
# === timestamp ============================================           #
timestamp="$(date '+%Y%m%d%H%M%S' | utconv)"                           #
message_date="$(echo $timestamp                                        |
                TZ=UTC+0 utconv -r                                     |
                cut -c 1-8                                             )"
meafter_date="$(echo $timestamp                                        |
                TZ=UTC+0 utconv -r                                     |
                cut -c 9-14                                            )"
message_time="${message_date}T${meafter_date}Z"                        #
tm_hdr="X-Amz-Date: ${message_time}"                                   #
# === 基本的な情報（変更の余地少あり）=========================           #
# GETのとき                                                             #
content_type="Content-Type:"                                           #
# POSTのとき                                                            #
# content_type="Content-Type: application/x-www-form-urlencoded"       #
# === 変更の余地あるもの、オプションによる可変予定==============           #
method="GET"                                                           #
aws_region="ap-northeast-1"                                            #
aws_service="s3"                                                       #
uri="/"                                                                #
aws_endpoint="$(printf "%s"                                            \
                       "${aws_service}-${aws_region}.amazonaws.com"    | 
                sed 's/\.\././'                                        )"
# === 設定をファイルか標準入力から読み込む =============================
#if [ -n "${1:-}" ]; then                                               #
#  file=$(cat $1)                                                       #
#else                                                                   #
#  file=$(while read line; do                                           #
#           echo "$line"                                                #
#           [ -z "$line" ] && break
#         done)                                                         #
#fi                                                                     #
file=
########################################################################
api_params=$(cat <<_______________APIPARAMS                            |
_______________APIPARAMS
             sed 's/^ *//'                                             )
request_payload="$(cat <<_____________________REQUESTPAYLOAD           |
                     ${file}
_____________________REQUESTPAYLOAD
                   sed 's/^ *//'                                       |
                   sed '/".*"/ s/ /--/'                                |
                   sed '/".*"/ s/ /_/g'                                |
                   sed '/".*"/ s/--/ /'                                |
                   awk '{printf "$.%s %s\n",$1,$2}'                    |
                   sed '/".*"/ s/_/ /g'                                | 
                   makrj.sh                                            |
                   sed 's/^,$//'                                       |
                   grep '^$'                                           )"
########################################################################
#メイン
########################################################################
canonical_uri=$(printf "%s" "$uri"                                     | 
                urlencode -r                                           |
                sed 's/%2[F]/\//g'                                     )
apip_enc=$(printf '%s\n' "${api_params}"                               |
           grep -v '^$'                                                |
           sort                                                        |
           urlencode -r                                                |
           sed 's/%1[Ee]/%0A/g'                                        | 
           sed 's/%3[Dd]/=/'                                           )
query_strings=$(printf '%s' "${apip_enc}"                              |
                tr '\n' '&'                                            )
request_payload_hash=$(printf "%s" "$request_payload"                  | 
                      "$CMD_OSSL" dgst -sha256 | self 2                )
rh_hdr="x-amz-content-sha256: $request_payload_hash"                   #
canonical_headers=$(cat <<______________________CANONICALHEADERS       |
                      ${content_type}
                      host:${aws_endpoint}
                      ${tm_hdr}
                      ${rh_hdr}
                      ${add_header}
______________________CANONICALHEADERS
                    sed 's/^ *//'                                      |
                    grep -v '^$'                                       |
                    awk -F: -v 'OFS=:' '{print tolower($1),$2}'        |
                    sed 's/\([^;]\) /\1/'                              |
                    sed 's/   *//'                                     |
                    grep -v '^$'                                       |
                    sort                                               )
signed_headers=$(printf "%s" "$canonical_headers"                      |
                 cut -d: -f1                                           |
                 sed 's/.*/&;/'                                        |
                 tr -d '\n'                                            |
                 sed 's/;$//'                                          )
canonical_request=$(cat <<______________________CANONICALREQUEST       |
                      ${method}
                      ${canonical_uri}
                      ${query_strings}
                      ${canonical_headers}

                      ${signed_headers}
                      ${request_payload_hash}
______________________CANONICALREQUEST
                    sed 's/^ *//'                                      )
canonical_request_hash=$(printf %s "$canonical_request"                |
                         "$CMD_OSSL" dgst -sha256 | self 2             )
credential_scope=$(printf '%s/%s/%s/aws4_request'                      \
                          "${message_date}"                            \
                          "${aws_region}"                              \
                          "${aws_service}"                             )
string_to_sign=$(cat <<___________________STRINGTOSIGN                 |
                   AWS4-HMAC-SHA256
                   ${message_time}
                   ${credential_scope}
                   ${canonical_request_hash}
___________________STRINGTOSIGN
                sed 's/^ *//'                                          )
signstep0=$(printf "$message_date"                                     | 
            "$CMD_OSSL" sha256                                         \
            -hmac "AWS4${u_secret}"               -hex                 |
            self 2                                                     )
signstep1=$(printf "$aws_region"                                       | 
            "$CMD_OSSL" sha256                                         \
            -mac HMAC -macopt hexkey:"$signstep0" -hex                 | 
            self 2                                                     )
signstep2=$(printf "$aws_service"                                      | 
            "$CMD_OSSL" sha256                                         \
            -mac HMAC -macopt hexkey:"$signstep1" -hex                 | 
            self 2                                                     )
signstep3=$(printf "aws4_request"                                      | 
            "$CMD_OSSL" sha256                                         \
            -mac HMAC -macopt hexkey:"$signstep2" -hex                 | 
            self 2                                                     )
signature=$(printf "%s" "$string_to_sign"                              | 
            "$CMD_OSSL" sha256                                         \
            -mac HMAC -macopt hexkey:"$signstep3" -hex                 | 
            self 2                                                     )
request_url="${aws_endpoint}${uri}?${query_strings:-}"                 #
[ -z "${query_strings}" ] && request_url=${request_url%'?'}            #
apires=$(printf 'Credential=%s/%s, SignedHeaders=%s, Signature=%s'     \
                "${u_key}"                                             \
                "${credential_scope}"                                  \
                "${signed_headers}"                                    \
                "${signature}"                                         |
         sed 's/^/Authorization: AWS4-HMAC-SHA256 /'                   |
         grep ^                                                        |
         while read -r oa_hdr; do                                      #
           if   [ -n "${CMD_WGET:-}" ]; then                           #
             "$CMD_WGET" -q -O - --method="$method"                    \
                         --header="$oa_hdr"                            \
                         --header="$tm_hdr"                            \
                         --header="$rh_hdr"                            \
                         --body-data="$request_payload"                \
                         "https://${request_url}"                    | #
             cat                                                       #
           elif [ -n "${CMD_CURL:-}" ]; then                           #
             "$CMD_CURL" -s -X "$method"                               \
                         -H "$oa_hdr"                                  \
                         -H "$tm_hdr"                                  \
                         -H "$rh_hdr"                                  \
                         "https://${request_url}"                      #
           fi                                                          #
         done                                                          |
         base64 --by-myself                                            )
#responce処理　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　  #
printf "%s" "$apires"                                                  |
base64 --by-myself -d                                                  #
